[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/sentry/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap_index.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "index, follow"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; style-src 'self';"
    X-Content-Type-Options = "nosniff"
    Content-Type = "text/html"