[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
      User-agent = "*"
      Allow = "/"
      X-Robots-Tag = "follow,index"

[[redirects]]
  from = "/sentry/*"
  to = "/sentry"
  status = 200