[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
      User-agent = "*"
      Allow = "/"
      X-Robots-Tag = "follow,index"

[[redirects]]
  from = "https://neo-nasa.netlify.app/sentry"
  to = "https://neo-nasa.netlify.app/sentry"
  status = 200
  force = true