[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/neomap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/sentry/*"
  to = "/index.html"
  status = 200