[build]
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
